name = "lumilink-mcp-staging"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_SECRET = "tXSf02Wk8n71wK4VTzcG4Yl9q4ihF3lU"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "lumilink_be_staging"
database_id = "136c0681-e743-453c-81ba-69fd57030829"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "LumiLinkMCP"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LumiLinkMCP"]

[[vectorize]]
binding = "VECTORIZE"
index_name = "lumi_staging"